### ISSUE TITLE
4x1 header vs 3x2 header for SiPM

### ISSUE THREAD

**Issue by HazenBabcock** [Open-Gamma-Project/Open-Gamma-Detector#13]
Thank you for the fascinating project. 

I have a question about the SiPM mount. The PCB of this project provides a connection for a 4x1 header to mount the SiPM. The apparent companion project [SiPM-Carrier-Board](https://github.com/Open-Gamma-Project/SiPM-Carrier-Board) has a 3x2 header. Is there something I don't understand about how these are supposed to work together? Or these projects are not actually related? 

If they are not related would you recommend including the additional VCC filtering that the SiPM-Carrier-Board provides? Or is the filtering that is already part of the PCB of this project sufficient?

**Comment by Phoenix1747** [comment]
Just uploaded the new carrier board PCB files (see e91c1b5157467a477cd668f4f80a455605af84f8 in [SiPM-Carrier-Board](https://github.com/Open-Gamma-Project/SiPM-Carrier-Board)). Like I said, the header is optional, but it's got the same pinout now too so you can plug it in if you use a male and a female header.
