### ISSUE TITLE
Consider removal of radiation trefoil from silkscreen design

### ISSUE THREAD

**Issue by litmus-ritten** [Open-Gamma-Project/Open-Gamma-Detector#9]
Hi, cool project!

Radiation trefoils typically designate that something is **a)** radioactive or **b)** contains radioactive materials. The presence of a radiation trefoil on this detector may give the mistaken impression to people unfamiliar with the device that the detector falls into one of these two categories.

**Comment by Phoenix1747** [comment]
You're completely correct, I have already removed it in the second revision of the board. It's coming very very soon 👍🏻 

Don't know why I added it in the first place to be honest, such an unnecessary thing.

**Comment by Phoenix1747** [comment]
See 70e3f56ebe0e749c65bd4cd521a97f2a77687a70.
